var swfVersionStr = "11.1.0";
var xiSwfUrlStr = "playerProductInstall.swf";
var flashvars = {};
var params = {};
params.quality = "high";
params.bgcolor = "#141414";
params.allowscriptaccess = "sameDomain";
params.allowfullscreen = "true";
var attributes = {};
attributes.id = "Main";
attributes.name = "Main";
attributes.align = "middle";
swfobject.embedSWF("Main.swf", "container", "100%", "100%", swfVersionStr, xiSwfUrlStr, flashvars, params, attributes);
swfobject.createCSS("#container", "display:block;text-align:left;");